version: "3"
services:
  db:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --sql_mode=""
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: Bup8S9rJ9uCrXGicydaQ
      DEMO_DATA: 1
      MAIL_TRANSPORT: debug
  web:
    build:
      context: .
      dockerfile: ./docker/studip/Dockerfile
      args:
        - ProxyUrl=https://studip.ceskar.xyz/

    depends_on:
      - db
    volumes:
      - web_data:/var/www/studip/data

    # Use port to redirect port
    ports:
      - "8032:80"

    restart: always
    environment:
      MYSQL_DATABASE: studip_db
      MYSQL_USER: studip_user
      MYSQL_PASSWORD: Bup8S9rJ9uCrXGicydaQ
      MYSQL_HOST: db
      STUDIP_MAIL_TRANSPORT: debug

      # Use automigrate to migrate your instance on startup
      AUTO_MIGRATE: 1

      #enable but fit IDP
      #it needs to be configured first in docker/studip/config_local.inc.php
      #and in docker/studip/simplesamlphp
      BUT_FIT_IDP: 1

      # Use proxy url OR autoproxy if run behind a proxy
      PROXY_URL: https://studip.ceskar.xyz/
      # AUTO_PROXY: 1

      # Demo data for your studip instance
      DEMO_DATA: 1

volumes:
  web_data: {}
  db_data: {}
