version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    labels: []
    versioning-strategy: lockfile-only
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: []
    versioning-strategy: lockfile-only
    open-pull-requests-limit: -1
    open-security-pull-requests-limit: -1
